### ISSUE TITLE
Support for BR v16

### ISSUE THREAD

**Issue by ghost** [bloomreach-forge/sitemapv2#4]
Dear sitemapv2 devs,

is there any information on when the plugin will support BR v16? The plugin uses the old javax.* namespace so I get an expected server error when trying to let the plugin generate a sitemap.

Cheers
Fred

**Comment by maxgda** [comment]
Hello @frsinn , we do not have a timeline for this upgrade. If it is urgent, it is possible for you to submit an MR for an upgrade and we can review and release it.

Have a nice day

**Comment by ghost** [comment]
@maxgda, I opened a pull request with the proposed changes. Feel free to review :)

**Comment by machak** [comment]
Thanks a lot @frsinn

**Comment by machak** [comment]
released 4.0.0 version
